import React, { useState } from 'react'
import { FileText, ChevronRight, ChevronLeft, CheckCircle, Download } from 'lucide-react'

const STEPS = [
  { id:1, title:'Organization Info', desc:'Tell us about your nonprofit' },
  { id:2, title:'Mission & Impact', desc:'Describe what you do and who you serve' },
  { id:3, title:'Project Description', desc:'What will this grant fund?' },
  { id:4, title:'Budget', desc:'How will the funds be used?' },
  { id:5, title:'Evaluation Plan', desc:'How will you measure success?' },
  { id:6, title:'Review & Export', desc:'Review your application draft' },
]

export default function ApplyWizard() {
  const [step, setStep] = useState(1)
  const [form, setForm] = useState({
    org_name:'', org_type:'501(c)(3)', ein:'', founded_year:'', address:'', website:'', contact_name:'', contact_email:'', contact_phone:'',
    mission:'', population_served:'', geographic_area:'', annual_budget:'', staff_count:'', volunteer_count:'',
    project_title:'', project_description:'', project_goals:'', project_timeline:'', project_start:'', project_end:'',
    total_request:'', personnel_cost:'', supplies_cost:'', indirect_cost:'', other_costs:'', budget_narrative:'',
    eval_methods:'', eval_metrics:'', eval_reporting:'',
  })

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }))

  const inputClass = "w-full border border-gray-200 rounded-xl px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400"
  const labelClass = "block text-sm font-semibold text-gray-700 mb-1"
  const textareaClass = "w-full border border-gray-200 rounded-xl px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400 resize-none"

  const exportDraft = () => {
    const text = `GRANT APPLICATION DRAFT
Generated by GrantBridge — ${new Date().toLocaleDateString()}
================================================

SECTION 1: ORGANIZATION INFORMATION
Organization Name: ${form.org_name}
Organization Type: ${form.org_type}
EIN: ${form.ein}
Year Founded: ${form.founded_year}
Address: ${form.address}
Website: ${form.website}
Contact: ${form.contact_name} | ${form.contact_email} | ${form.contact_phone}

SECTION 2: MISSION & IMPACT
Mission Statement: ${form.mission}
Population Served: ${form.population_served}
Geographic Area: ${form.geographic_area}
Annual Budget: ${form.annual_budget}
Staff: ${form.staff_count} | Volunteers: ${form.volunteer_count}

SECTION 3: PROJECT DESCRIPTION
Project Title: ${form.project_title}
Project Description:
${form.project_description}

Goals & Objectives:
${form.project_goals}

Timeline: ${form.project_start} to ${form.project_end}
${form.project_timeline}

SECTION 4: BUDGET
Total Grant Request: ${form.total_request}
Personnel Costs: ${form.personnel_cost}
Supplies & Equipment: ${form.supplies_cost}
Indirect/Overhead: ${form.indirect_cost}
Other Costs: ${form.other_costs}

Budget Narrative:
${form.budget_narrative}

SECTION 5: EVALUATION PLAN
Evaluation Methods: ${form.eval_methods}
Key Metrics: ${form.eval_metrics}
Reporting Plan: ${form.eval_reporting}

================================================
Generated by GrantBridge — Free for all nonprofits
github.com/andrewhartman1998-cell/healthbridge-universal
`
    const blob = new Blob([text], { type:'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `grant-application-${form.org_name.replace(/\s+/g,'-') || 'draft'}.txt`
    a.click()
  }

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-800 mb-2">📝 Grant Application Wizard</h1>
        <p className="text-gray-500">Step-by-step guidance through every section of a grant application. Fill it out and export a ready-to-submit draft.</p>
      </div>

      {/* Progress */}
      <div className="flex items-center gap-1 mb-8 overflow-x-auto pb-2">
        {STEPS.map((s, i) => (
          <React.Fragment key={s.id}>
            <button onClick={() => setStep(s.id)}
              className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium whitespace-nowrap transition-all ${step === s.id ? 'bg-indigo-700 text-white' : step > s.id ? 'bg-indigo-100 text-indigo-700' : 'bg-gray-100 text-gray-500'}`}>
              {step > s.id ? <CheckCircle size={13} /> : <span>{s.id}</span>}
              {s.title}
            </button>
            {i < STEPS.length - 1 && <ChevronRight size={14} className="text-gray-300 shrink-0" />}
          </React.Fragment>
        ))}
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 mb-6">
        <h2 className="text-lg font-bold text-gray-800 mb-1">{STEPS[step-1].title}</h2>
        <p className="text-gray-500 text-sm mb-6">{STEPS[step-1].desc}</p>

        {step === 1 && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="md:col-span-2"><label className={labelClass}>Organization Name *</label><input value={form.org_name} onChange={e=>set('org_name',e.target.value)} placeholder="e.g. Helping Hands Foundation" className={inputClass} /></div>
            <div><label className={labelClass}>Organization Type</label><select value={form.org_type} onChange={e=>set('org_type',e.target.value)} className={inputClass}><option>501(c)(3)</option><option>501(c)(4)</option><option>Fiscal Sponsorship</option><option>Other</option></select></div>
            <div><label className={labelClass}>EIN (Tax ID)</label><input value={form.ein} onChange={e=>set('ein',e.target.value)} placeholder="XX-XXXXXXX" className={inputClass} /></div>
            <div><label className={labelClass}>Year Founded</label><input value={form.founded_year} onChange={e=>set('founded_year',e.target.value)} placeholder="2015" className={inputClass} /></div>
            <div><label className={labelClass}>Annual Operating Budget</label><input value={form.annual_budget} onChange={e=>set('annual_budget',e.target.value)} placeholder="$250,000" className={inputClass} /></div>
            <div className="md:col-span-2"><label className={labelClass}>Address</label><input value={form.address} onChange={e=>set('address',e.target.value)} placeholder="123 Main St, Chicago, IL 60601" className={inputClass} /></div>
            <div><label className={labelClass}>Website</label><input value={form.website} onChange={e=>set('website',e.target.value)} placeholder="www.helpinghands.org" className={inputClass} /></div>
            <div><label className={labelClass}>Primary Contact Name</label><input value={form.contact_name} onChange={e=>set('contact_name',e.target.value)} placeholder="Jane Smith" className={inputClass} /></div>
            <div><label className={labelClass}>Contact Email</label><input value={form.contact_email} onChange={e=>set('contact_email',e.target.value)} placeholder="jane@helpinghands.org" className={inputClass} /></div>
            <div><label className={labelClass}>Contact Phone</label><input value={form.contact_phone} onChange={e=>set('contact_phone',e.target.value)} placeholder="(312) 555-0100" className={inputClass} /></div>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-4">
            <div><label className={labelClass}>Mission Statement *</label><textarea value={form.mission} onChange={e=>set('mission',e.target.value)} rows={4} placeholder="In 2–3 sentences, describe your organization's core mission and the change you seek to create in the world..." className={textareaClass} /></div>
            <div><label className={labelClass}>Population Served *</label><textarea value={form.population_served} onChange={e=>set('population_served',e.target.value)} rows={3} placeholder="Who specifically does your organization serve? Include demographics, numbers, and any barriers they face..." className={textareaClass} /></div>
            <div><label className={labelClass}>Geographic Area</label><input value={form.geographic_area} onChange={e=>set('geographic_area',e.target.value)} placeholder="e.g. South Side of Chicago, or statewide Illinois, or nationwide" className={inputClass} /></div>
            <div className="grid grid-cols-2 gap-4">
              <div><label className={labelClass}>Full-Time Staff</label><input value={form.staff_count} onChange={e=>set('staff_count',e.target.value)} placeholder="12" className={inputClass} /></div>
              <div><label className={labelClass}>Volunteers</label><input value={form.volunteer_count} onChange={e=>set('volunteer_count',e.target.value)} placeholder="45" className={inputClass} /></div>
            </div>
          </div>
        )}

        {step === 3 && (
          <div className="space-y-4">
            <div><label className={labelClass}>Project Title *</label><input value={form.project_title} onChange={e=>set('project_title',e.target.value)} placeholder="e.g. Expanding Food Pantry Capacity in the South Side" className={inputClass} /></div>
            <div><label className={labelClass}>Project Description *</label><textarea value={form.project_description} onChange={e=>set('project_description',e.target.value)} rows={5} placeholder="Describe the project in detail. What problem does it solve? Why is it needed? What will you do? What will change as a result?..." className={textareaClass} /></div>
            <div><label className={labelClass}>Goals & Objectives</label><textarea value={form.project_goals} onChange={e=>set('project_goals',e.target.value)} rows={4} placeholder="List 3–5 specific, measurable goals. E.g.: Goal 1: Distribute 10,000 meals per month by end of Year 1..." className={textareaClass} /></div>
            <div className="grid grid-cols-2 gap-4">
              <div><label className={labelClass}>Project Start Date</label><input type="date" value={form.project_start} onChange={e=>set('project_start',e.target.value)} className={inputClass} /></div>
              <div><label className={labelClass}>Project End Date</label><input type="date" value={form.project_end} onChange={e=>set('project_end',e.target.value)} className={inputClass} /></div>
            </div>
            <div><label className={labelClass}>Timeline / Milestones</label><textarea value={form.project_timeline} onChange={e=>set('project_timeline',e.target.value)} rows={3} placeholder="Month 1–3: Hire staff, set up space. Month 4–6: Launch program. Month 7–12: Full operations, 1,000 clients served..." className={textareaClass} /></div>
          </div>
        )}

        {step === 4 && (
          <div className="space-y-4">
            <div className="bg-indigo-50 rounded-xl p-4 text-sm text-indigo-800 mb-2">💡 <strong>Tip:</strong> Most funders want to see that 80–85% goes directly to programs (not admin). Keep indirect costs under 15–20%.</div>
            <div><label className={labelClass}>Total Grant Request *</label><input value={form.total_request} onChange={e=>set('total_request',e.target.value)} placeholder="$50,000" className={inputClass} /></div>
            <div className="grid grid-cols-2 gap-4">
              <div><label className={labelClass}>Personnel / Salaries</label><input value={form.personnel_cost} onChange={e=>set('personnel_cost',e.target.value)} placeholder="$35,000" className={inputClass} /></div>
              <div><label className={labelClass}>Supplies & Equipment</label><input value={form.supplies_cost} onChange={e=>set('supplies_cost',e.target.value)} placeholder="$8,000" className={inputClass} /></div>
              <div><label className={labelClass}>Indirect / Overhead (max 15%)</label><input value={form.indirect_cost} onChange={e=>set('indirect_cost',e.target.value)} placeholder="$5,000" className={inputClass} /></div>
              <div><label className={labelClass}>Other Costs</label><input value={form.other_costs} onChange={e=>set('other_costs',e.target.value)} placeholder="$2,000" className={inputClass} /></div>
            </div>
            <div><label className={labelClass}>Budget Narrative *</label><textarea value={form.budget_narrative} onChange={e=>set('budget_narrative',e.target.value)} rows={5} placeholder="Explain each line item. Why is it needed? How was the cost calculated? E.g.: 'Program Coordinator (0.5 FTE at $45,000/yr = $22,500) — responsible for day-to-day program operations and client intake.'" className={textareaClass} /></div>
          </div>
        )}

        {step === 5 && (
          <div className="space-y-4">
            <div className="bg-indigo-50 rounded-xl p-4 text-sm text-indigo-800 mb-2">💡 <strong>Tip:</strong> Funders want to know you'll measure results. Use specific numbers: "We will serve 500 families" not "We will help many families."</div>
            <div><label className={labelClass}>Evaluation Methods</label><textarea value={form.eval_methods} onChange={e=>set('eval_methods',e.target.value)} rows={4} placeholder="How will you collect data? Surveys, intake forms, service logs, pre/post assessments, attendance records..." className={textareaClass} /></div>
            <div><label className={labelClass}>Key Metrics / Outcomes</label><textarea value={form.eval_metrics} onChange={e=>set('eval_metrics',e.target.value)} rows={4} placeholder="List specific, measurable outcomes. E.g.: 500 families receive monthly food boxes. 85% of participants report reduced food insecurity. 200 people connected to SNAP benefits..." className={textareaClass} /></div>
            <div><label className={labelClass}>Reporting Plan</label><textarea value={form.eval_reporting} onChange={e=>set('eval_reporting',e.target.value)} rows={3} placeholder="How and when will you report results to the funder? E.g.: Quarterly progress reports submitted via email. Final report with data dashboard within 30 days of project end..." className={textareaClass} /></div>
          </div>
        )}

        {step === 6 && (
          <div>
            <div className="bg-green-50 border border-green-200 rounded-xl p-4 mb-6">
              <p className="text-green-800 font-semibold">✅ Your draft is ready!</p>
              <p className="text-green-700 text-sm mt-1">Review the summary below, then download your application draft as a text file to copy into any grant portal.</p>
            </div>
            <div className="space-y-3 text-sm">
              {[['Organization', form.org_name || '(not entered)'],['EIN', form.ein || '(not entered)'],['Project Title', form.project_title || '(not entered)'],['Grant Request', form.total_request || '(not entered)'],['Timeline', form.project_start && form.project_end ? `${form.project_start} to ${form.project_end}` : '(not entered)']].map(([k,v]) => (
                <div key={k} className="flex gap-3 py-2 border-b border-gray-100">
                  <span className="font-semibold text-gray-600 w-36 shrink-0">{k}</span>
                  <span className="text-gray-800">{v}</span>
                </div>
              ))}
            </div>
            <button onClick={exportDraft} className="mt-6 w-full bg-indigo-700 text-white font-bold py-3 rounded-xl hover:bg-indigo-800 transition-all flex items-center justify-center gap-2">
              <Download size={18} /> Download Application Draft (.txt)
            </button>
          </div>
        )}
      </div>

      {/* Nav buttons */}
      <div className="flex justify-between">
        <button onClick={() => setStep(s => Math.max(1,s-1))} disabled={step === 1}
          className="flex items-center gap-2 px-6 py-2 border border-gray-200 rounded-xl text-sm font-medium text-gray-600 hover:bg-gray-50 disabled:opacity-40">
          <ChevronLeft size={16} /> Previous
        </button>
        {step < 6
          ? <button onClick={() => setStep(s => Math.min(6,s+1))} className="flex items-center gap-2 px-6 py-2 bg-indigo-700 text-white rounded-xl text-sm font-medium hover:bg-indigo-800">
              Next <ChevronRight size={16} />
            </button>
          : <button onClick={exportDraft} className="flex items-center gap-2 px-6 py-2 bg-green-600 text-white rounded-xl text-sm font-medium hover:bg-green-700">
              <Download size={16} /> Export Draft
            </button>
        }
      </div>
    </div>
  )
}
